### PR TITLE
Update Wails to latest version to fix webkit2gtk issue, update to go 1.16

### LINKED ISSUE #54: Empty dark gray screen on startup
Using 0.4.0 on Linux, I get an empty, dark gray (regular background colour) on startup, and nothing else. Starting from a terminal, I get this (and only this):

```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
```

When closing the window, the process exits normally (0).

I didn't find any flag to make it more verbose or anything. It used to work on the same machine a few weeks ago, and can't figure out what might have changed since then. I tried removing `~/.cache/wombat` and `~/.local/share/Wombat`, it didn't make a difference.

What can I do to get more insights to troubleshoot this?

### PR DESCRIPTION
**Pull request by aschey**
Resolves #54 

I updated Wails to the latest version to address [this issue](https://github.com/wailsapp/wails/issues/658) caused by a change in a new version of webkit2gtk. I was also having an issue where the UI wasn't showing up at all which I think is related to [this other Wails issue related to Mewn](https://github.com/wailsapp/wails/issues/640). [Mewn is now deprecated](https://github.com/leaanthony/mewn) and the approach Wails is taking is to replace Mewn with Go 1.16's native embedding functionality so that's the approach I followed here too. 

Let me know if you need me to change anything, thanks!

### CODE REVIEW

**Comment by aschey** [comment]
I just ran this on Windows and found another issue. The Wails change to fix Webkit also broke Windows due to differences in strict mode with IE. I just created a PR to wails to resolve that: https://github.com/wailsapp/wails/pull/669 and I will update this PR with the newest version of Wails once that gets merged if this is still open.

**Comment by aschey** [comment]
Wails PR is merged and released. Linux and Windows builds should both be good now.

**Comment by aschey** [comment]
@rogchap Any chance you could take a look at this when you have some time so we can get builds fixed on Linux?

**Review by rogchap — APPROVED** [review]

**Comment by Kernald** [comment]
Could we get a release tagged with this fix please? It would help updating the Archlinux package :-)

**Pull request merged**
